In [1]:
%load_ext autoreload
%autoreload complete

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import importlib as imp
# specific classes for training, validating, and testing, 
# as described in LearningToBalance original code
train_class_names = [
    'train', 'skyscraper', 'turtle', 'raccoon', 'spider', 'orange', 'castle', 'keyboard',
    'clock', 'pear', 'girl', 'seal', 'elephant', 'apple', 'aquarium_fish', 'bus',
    'mushroom', 'possum', 'squirrel', 'chair', 'tank', 'plate', 'wolf', 'road', 'mouse',
    'boy', 'shrew', 'couch', 'sunflower', 'tiger', 'caterpillar', 'lion', 'streetcar',
    'lawn_mower', 'tulip', 'forest', 'dolphin', 'cockroach', 'bear', 'porcupine', 'bee',
    'hamster', 'lobster', 'bowl', 'can', 'bottle', 'trout', 'snake', 'bridge',
    'pine_tree', 'skunk', 'lizard', 'cup', 'kangaroo', 'oak_tree', 'dinosaur', 'rabbit',
    'orchid', 'willow_tree', 'ray', 'palm_tree', 'mountain', 'house', 'cloud'
    ]
valid_class_names = [
    'otter', 'motorcycle', 'television', 'lamp', 'crocodile', 'shark', 'butterfly', 'sea',
    'beaver', 'beetle', 'tractor', 'flatfish', 'maple_tree', 'camel', 'crab', 'cattle'
    ]
test_class_names = [
    'baby', 'bed', 'bicycle', 'chimpanzee', 'fox', 'leopard', 'man', 'pickup_truck',
    'plain', 'poppy', 'rocket', 'rose', 'snail', 'sweet_pepper', 'table', 'telephone',
    'wardrobe', 'whale', 'woman', 'worm'
    ]
# 
LABEL_NAMES : list[str] = ['apple', 'aquarium_fish', 'baby', 'bear', 'beaver', 'bed', 'bee', 'beetle', 'bicycle', 'bottle', 'bowl', 'boy', 'bridge', 'bus', 'butterfly', 'camel', 'can', 'castle', 'caterpillar', 'cattle', 'chair', 'chimpanzee', 'clock', 'cloud', 'cockroach', 'couch', 'crab', 'crocodile', 'cup', 'dinosaur', 'dolphin', 'elephant', 'flatfish', 'forest', 'fox', 'girl', 'hamster', 'house', 'kangaroo', 'keyboard', 'lamp', 'lawn_mower', 'leopard', 'lion', 'lizard', 'lobster', 'man', 'maple_tree', 'motorcycle', 'mountain', 'mouse', 'mushroom', 'oak_tree', 'orange', 'orchid', 'otter', 'palm_tree', 'pear', 'pickup_truck', 'pine_tree', 'plain', 'plate', 'poppy', 'porcupine', 'possum', 'rabbit', 'raccoon', 'ray', 'road', 'rocket', 'rose', 'sea', 'seal', 'shark', 'shrew', 'skunk', 'skyscraper', 'snail', 'snake', 'spider', 'squirrel', 'streetcar', 'sunflower', 'sweet_pepper', 'table', 'tank', 'telephone', 'television', 'tiger', 'tractor', 'train', 'trout', 'tulip', 'turtle', 'wardrobe', 'whale', 'willow_tree', 'wolf', 'woman', 'worm']


In [19]:
# verify that Data/get_dataloader works!
from Data import get_dataloader

max_number_of_shot = 7
number_of_query = 2
way = 3
total_task = 9
batch_size = 5
some_dataloader = get_dataloader(valid_class_names, max_number_of_shot, number_of_query, way, total_tasks=total_task, batch_size=batch_size)
# test_index = 9
# test_image = d[LABEL_NAMES.index((valid_class_names[0]))]['image'][test_index]
# test_label = LABEL_NAMES[d[LABEL_NAMES.index((valid_class_names[0]))]['label'][test_index]]
# f, ax = plt.subplots(figsize=(2, 2))
# ax.imshow(test_image)
# ax.set_title(test_label)
# c = 0
# for i, task_batch in enumerate(some_dataloader):
#     print(f"TASK batch")
#     print(f"type:   {type(task_batch)}")
#     print(f"length: {len(task_batch)}")
#     for c in range(batch_size):
#         print(f"\ttask {c}")
#         # print(task[0].shape)
#         # print(task[1].shape)
#         # print(task[2].shape)
#         # print(task[3].shape)
#         # print(task[4].shape)
#         img_supp = task_batch[0][c]
#         lbl_supp = task_batch[1][c]
#         img_quer = task_batch[2][c]
#         lbl_quer = task_batch[3][c]
#         # print(lbl_quer)
#         print(f"\tshape of img_supp: {img_supp.shape}")
#         print(f"\tshape of lbl_supp: {lbl_supp.shape}")
#         print(f"\tshape of img_quer: {img_quer.shape}")
#         print(f"\tshape of lbl_quer: {lbl_quer.shape}")
#     if c == 1:
#         break

TASK batch
type:   <class 'list'>
length: 4
	task 0
	shape of img_supp: torch.Size([21, 32, 32, 3])
	shape of lbl_supp: torch.Size([21])
	shape of img_quer: torch.Size([6, 32, 32, 3])
	shape of lbl_quer: torch.Size([6])
	task 1
	shape of img_supp: torch.Size([21, 32, 32, 3])
	shape of lbl_supp: torch.Size([21])
	shape of img_quer: torch.Size([6, 32, 32, 3])
	shape of lbl_quer: torch.Size([6])
	task 2
	shape of img_supp: torch.Size([21, 32, 32, 3])
	shape of lbl_supp: torch.Size([21])
	shape of img_quer: torch.Size([6, 32, 32, 3])
	shape of lbl_quer: torch.Size([6])
	task 3
	shape of img_supp: torch.Size([21, 32, 32, 3])
	shape of lbl_supp: torch.Size([21])
	shape of img_quer: torch.Size([6, 32, 32, 3])
	shape of lbl_quer: torch.Size([6])
	task 4
	shape of img_supp: torch.Size([21, 32, 32, 3])
	shape of lbl_supp: torch.Size([21])
	shape of img_quer: torch.Size([6, 32, 32, 3])
	shape of lbl_quer: torch.Size([6])


In [69]:
import model
import Data
imp.reload(Data)
imp.reload(model)
# data_name : str = 'cifar'
number_of_inner_gradient_steps: int = 1
ways: int = 7
shots: int = 10
query: int = 3
total_train_task = 80
total_valid_task = 10
total_test_task = 20
inner_learning_rate: float = 1e-4
outer_learning_rate: float = 1e-4
batch_size = 5
m = model.LearningToBalance(data_name='cifar', number_of_inner_gradient_steps=number_of_inner_gradient_steps, 
        ways=ways, shots=shots, inner_learning_rate=inner_learning_rate, outer_learning_rate=outer_learning_rate, batch_size=batch_size)
train_loss, valid_loss, train_accuracy, valid_accuracy = m.train(
        train_dataloader=Data.get_dataloader(train_class_names, shots, query, ways, total_train_task, batch_size),
        valid_dataloader=Data.get_dataloader(valid_class_names, shots, query, ways, total_valid_task, batch_size))
test_loss, test_accuracy = m.test(test_dataloader=
       Data.get_dataloader(test_class_names, shots, query, ways, total_test_task, batch_size))
f, ax = plt.subplots(figsize=(4, 4), nrows=1, ncols=3)
ax[0].plot(train_loss)
ax[1].plot(valid_loss)
ax[2].plot(test_loss)

model, get_parameter, generating params theta
model, get_parameter, generating params alpha
T-R-A-I-N
train_dataloader length? 16
valid_dataloader length? 2


/home/jason/anaconda3/envs/new/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 47.54 GiB total capacity; 23.83 GiB already allocated; 6.75 MiB free; 25.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [ ]:
"""parallelization example, using vmap!"""
# def div(x : torch.Tensor):
#     return x + 1
# a = torch.Tensor([1])
# b = torch.Tensor([2])
# c = torch.Tensor([3])
# d = torch.Tensor([4])

# f = lambda x : div(x)
# e, f, g, h = torch.vmap(func=div)(torch.stack([a, b, c, d]))
# print(e)
# print(f)
# print(g)
# print(h)

tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [ ]:
"""simple test of inference network"""
# import encoder
# imp.reload(encoder)
# ways = 3
# shots = 5
# model = encoder.InferenceNetwork(ways=ways, shots=shots, data_name='cifar',
#                          need_g=True, need_o=True, need_s=True, need_z=True)
# omega, gamma, zeta, KL = model(batch_of_images.float(), batch_of_labels.float(), True)
# print(f"omega: {omega.size()}, corresponding to ways: {ways}")
# print(f"gamma: ")
# for key in gamma.keys():
#     print(f"\t{key}: {gamma[key].size()}")
# print(f"zeta: ")
# for key in zeta.keys():
#     print(f"\t{key}: {zeta[key].size()}")
# print(f"KL: {KL}")

omega: torch.Size([3]), corresponding to ways: 3
gamma: 
	convolution1_weight: torch.Size([1])
	convolution1_bias: torch.Size([1])
	convolution2_weight: torch.Size([1])
	convolution2_bias: torch.Size([1])
	convolution3_weight: torch.Size([1])
	convolution3_bias: torch.Size([1])
	convolution4_weight: torch.Size([1])
	convolution4_bias: torch.Size([1])
	dense_weight: torch.Size([1])
	dense_bias: torch.Size([1])
zeta: 
	convolution1_weight: torch.Size([32])
	convolution1_bias: torch.Size([32])
	convolution2_weight: torch.Size([32])
	convolution2_bias: torch.Size([32])
	convolution3_weight: torch.Size([32])
	convolution3_bias: torch.Size([32])
	convolution4_weight: torch.Size([32])
	convolution4_bias: torch.Size([32])
KL: 3075.778564453125
